---
- name: Check for updates on all servers
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ubuntu - List available updates
      shell: apt list --upgradable 2>/dev/null | tail -n +2
      register: ubuntu_updates
      when: ansible_os_family == "Debian"

    - name: AlmaLinux - List available updates
      shell: dnf list updates -q
      register: almalinux_updates
      when: ansible_os_family == "RedHat"

    - name: Collect update results (per server)
      set_fact:
        server_report: |
          Server: {{ inventory_hostname }}
          {% if ansible_os_family == "Debian" %}
          {{ ubuntu_updates.stdout }}
          {% elif ansible_os_family == "RedHat" %}
          {{ almalinux_updates.stdout }}
          {% endif %}

- name: Create update report and send email  # Combined play
  hosts: localhost
  connection: local
  tasks:
    - name: Gather server reports  # Simplified with Jinja2
      set_fact:
        all_reports: "{{ groups['all'] | map('extract', hostvars) | map('attribute', 'server_report') | join('\n') }}"

    - name: Create update report file
      blockinfile:
        path: /tmp/update_reports/update_report.txt  # Or reports/update_report.txt if 'reports' dir exists in your playbook's dir
        create: yes
        block: "{{ all_reports }}"

    - name: Send email
      mail:
        to: "netadmin@htown5711.duckdns.org"
        subject: "Update Report for All Servers"
        body: "{{ lookup('file', '/tmp/update_reports/update_report.txt') }}"  # Or reports/update_report.txt
        from: "semaphore@htown5711.duckdns.org"
