---
- name: Create devops user with sudo privileges, setup SSH directory, add public key, and allow passwordless sudo
  hosts: all  # Replace with your target server group or IP in the Ansible inventory
  become: yes  # Allows Ansible to run tasks with elevated privileges

  vars:
    devops_password: "{{ 'P@ssword' | password_hash('sha512') }}"  # Encrypts the password
    devops_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCod3mPDicT5Lu8s/BDi+xWRgMBZdcdk6jMCbfu+BN5CFhbR6aY82r3xz07FMBG3UZIiFdXij5A1UjbpINf+PWGTf83u3Q2CvJs4eMeAgTjkSnQy3cl/WzoUAbjgZF0iqFumNuZx4tGLgBXcm6VV8Vn9fssPaLRUAK8x45k7MNwCASD81HS/UiP7oA/l5Rwp/2iKicC6SVzHHvrmBy1MKcB9sqE/G8tNaQ7pvGOvwkM6aAvt50KUQN4kU0271UG/RT31N05yIrsT6TMpKmDTsxasVhmNbrdmWUu90951eSqv94eXxEEUi7hUiYEFdf/qd6aQI9xhakHkyey8Jjo7fcpiKuyw46/CdPXfiIGknXaUDVS2w9IkvaEcgPHOgOsqyGxNNkilMW7Pi5OXtaMiihUvX9kC2//f+FBJtIhk0NpZL521L/5HYovXnQ7NTwTcMI+q6gqtL68waneI43/SPLkiwly59RWaFPyGgkIw5NlMr4IXei+aLOXfnzSBGbclbyEBn98XGfK8mLIVrsuamF3cG1ksB1Vy+vhSkRb05EB5BUtaOvpWyw2gNHx1YbsjGkGAnhU/ZNQxEYmlz84Z2cI3g104xKoxLQ2j8T35Y/+SGGJnNX+tDOkr8f8VeZuddBY71Ki0BkJydNpuUKT3cPjxt/MHdHO5WTcm2v45rke5w== admin1@ansible-srvr"  # Replace with your actual SSH public key
    devops_shell: "/bin/bash"  # Specify the default shell here

  tasks:
    - name: Ensure the devops user is present on Ubuntu and AlmaLinux
      ansible.builtin.user:
        name: devops
        password: "{{ devops_password }}"
        shell: "{{ devops_shell }}"  # Set the default shell
        state: present
      when: ansible_os_family in ['Debian', 'RedHat']  # This covers Ubuntu (Debian) and AlmaLinux (RedHat)

    - name: Add devops user to sudo group on Ubuntu
      ansible.builtin.user:
        name: devops
        groups: sudo
        append: yes
      when: ansible_os_family == 'Debian'

    - name: Add devops user to wheel group on AlmaLinux
      ansible.builtin.user:
        name: devops
        groups: wheel
        append: yes
      when: ansible_os_family == 'RedHat'

    - name: Create .ssh directory for devops user
      ansible.builtin.file:
        path: /home/devops/.ssh
        state: directory
        owner: devops
        group: devops
        mode: '0700'  # Restricts access to the owner for security

    - name: Add SSH public key to authorized_keys for devops user
      ansible.builtin.copy:
        content: "{{ devops_ssh_key }}"
        dest: /home/devops/.ssh/authorized_keys
        owner: devops
        group: devops
        mode: '0600'  # Sets permissions to read/write for owner only

    - name: Allow devops user passwordless sudo on Ubuntu
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/devops
        create: yes
        line: "devops ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      when: ansible_os_family == 'Debian'

    - name: Allow devops user passwordless sudo on AlmaLinux
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/devops
        create: yes
        line: "devops ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
      when: ansible_os_family == 'RedHat'
