---
- name: Perform dist-upgrade and reboot if needed
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Update the package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if a reboot is required
      ansible.builtin.reboot:
      when: reboot_required.stat.exists
