---
- name: Ping and update non-core and non-kernel packages on Ubuntu and AlmaLinux
  hosts: all  # Replace with your target group or hosts in the inventory
  become: yes  # Run tasks with elevated privileges

  tasks:
    - name: Ping each device to check if it is online
      ansible.builtin.ping:
      register: ping_result
      failed_when: ping_result.ping != "pong"

    - name: Skip the host if it is unreachable
      meta: end_host
      when: ping_result.ping != "pong"

    - name: Update non-core and non-kernel packages on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Hold kernel packages on Ubuntu
      ansible.builtin.shell: |
        apt-mark hold linux-generic linux-headers-generic linux-image-generic
      when: ansible_os_family == "Debian"

    - name: Update non-core and non-kernel packages on AlmaLinux
      ansible.builtin.dnf:
        name: "*"
        exclude: "kernel*,centos*,almalinux*,redhat*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Unhold kernel packages on Ubuntu after update
      ansible.builtin.shell: |
        apt-mark unhold linux-generic linux-headers-generic linux-image-generic
      when: ansible_os_family == "Debian"
